//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 8 files.
  struct file {
    /// Resource file `CLARO.png`.
    static let claroPng = Rswift.FileResource(bundle: R.hostingBundle, name: "CLARO", pathExtension: "png")
    /// Resource file `CNT.png`.
    static let cntPng = Rswift.FileResource(bundle: R.hostingBundle, name: "CNT", pathExtension: "png")
    /// Resource file `Entitlements.plist`.
    static let entitlementsPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Entitlements", pathExtension: "plist")
    /// Resource file `MOVISTAR.png`.
    static let movistarPng = Rswift.FileResource(bundle: R.hostingBundle, name: "MOVISTAR", pathExtension: "png")
    /// Resource file `beep.wav`.
    static let beepWav = Rswift.FileResource(bundle: R.hostingBundle, name: "beep", pathExtension: "wav")
    /// Resource file `claxon.mp3`.
    static let claxonMp3 = Rswift.FileResource(bundle: R.hostingBundle, name: "claxon", pathExtension: "mp3")
    /// Resource file `ds_digital`.
    static let ds_digital = Rswift.FileResource(bundle: R.hostingBundle, name: "ds_digital", pathExtension: "")
    /// Resource file `xoalogo1.png`.
    static let xoalogo1Png = Rswift.FileResource(bundle: R.hostingBundle, name: "xoalogo1", pathExtension: "png")
    
    /// `bundle.url(forResource: "CLARO", withExtension: "png")`
    static func claroPng(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.claroPng
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "CNT", withExtension: "png")`
    static func cntPng(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cntPng
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Entitlements", withExtension: "plist")`
    static func entitlementsPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.entitlementsPlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "MOVISTAR", withExtension: "png")`
    static func movistarPng(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.movistarPng
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "beep", withExtension: "wav")`
    static func beepWav(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.beepWav
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "claxon", withExtension: "mp3")`
    static func claxonMp3(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.claxonMp3
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "ds_digital", withExtension: "")`
    static func ds_digital(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ds_digital
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "xoalogo1", withExtension: "png")`
    static func xoalogo1Png(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.xoalogo1Png
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 58 images.
  struct image {
    /// Image `CLARO`.
    static let clarO = Rswift.ImageResource(bundle: R.hostingBundle, name: "CLARO")
    /// Image `CNT`.
    static let cnT = Rswift.ImageResource(bundle: R.hostingBundle, name: "CNT")
    /// Image `MOVISTAR`.
    static let movistaR = Rswift.ImageResource(bundle: R.hostingBundle, name: "MOVISTAR")
    /// Image `backIcon`.
    static let backIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "backIcon")
    /// Image `callCenter`.
    static let callCenter = Rswift.ImageResource(bundle: R.hostingBundle, name: "callCenter")
    /// Image `camion_icon`.
    static let camion_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "camion_icon")
    /// Image `camion`.
    static let camion = Rswift.ImageResource(bundle: R.hostingBundle, name: "camion")
    /// Image `camioneta_icon`.
    static let camioneta_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "camioneta_icon")
    /// Image `camioneta`.
    static let camioneta = Rswift.ImageResource(bundle: R.hostingBundle, name: "camioneta")
    /// Image `chofer`.
    static let chofer = Rswift.ImageResource(bundle: R.hostingBundle, name: "chofer")
    /// Image `clave`.
    static let clave = Rswift.ImageResource(bundle: R.hostingBundle, name: "clave")
    /// Image `close`.
    static let close = Rswift.ImageResource(bundle: R.hostingBundle, name: "close")
    /// Image `compartir`.
    static let compartir = Rswift.ImageResource(bundle: R.hostingBundle, name: "compartir")
    /// Image `contactoIcon`.
    static let contactoIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "contactoIcon")
    /// Image `costo`.
    static let costo = Rswift.ImageResource(bundle: R.hostingBundle, name: "costo")
    /// Image `destinoIcon`.
    static let destinoIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "destinoIcon")
    /// Image `detalleIcon`.
    static let detalleIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "detalleIcon")
    /// Image `detalles`.
    static let detalles = Rswift.ImageResource(bundle: R.hostingBundle, name: "detalles")
    /// Image `distancia`.
    static let distancia = Rswift.ImageResource(bundle: R.hostingBundle, name: "distancia")
    /// Image `driverIcon`.
    static let driverIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "driverIcon")
    /// Image `evaluar`.
    static let evaluar = Rswift.ImageResource(bundle: R.hostingBundle, name: "evaluar")
    /// Image `furgon_icon`.
    static let furgon_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "furgon_icon")
    /// Image `furgon`.
    static let furgon = Rswift.ImageResource(bundle: R.hostingBundle, name: "furgon")
    /// Image `furgoneta_icon`.
    static let furgoneta_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "furgoneta_icon")
    /// Image `furgoneta`.
    static let furgoneta = Rswift.ImageResource(bundle: R.hostingBundle, name: "furgoneta")
    /// Image `grua_icon`.
    static let grua_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "grua_icon")
    /// Image `grua`.
    static let grua = Rswift.ImageResource(bundle: R.hostingBundle, name: "grua")
    /// Image `header`.
    static let header = Rswift.ImageResource(bundle: R.hostingBundle, name: "header")
    /// Image `home`.
    static let home = Rswift.ImageResource(bundle: R.hostingBundle, name: "home")
    /// Image `infoMenu`.
    static let infoMenu = Rswift.ImageResource(bundle: R.hostingBundle, name: "infoMenu")
    /// Image `info`.
    static let info = Rswift.ImageResource(bundle: R.hostingBundle, name: "info")
    /// Image `launch`.
    static let launch = Rswift.ImageResource(bundle: R.hostingBundle, name: "launch")
    /// Image `llamar`.
    static let llamar = Rswift.ImageResource(bundle: R.hostingBundle, name: "llamar")
    /// Image `loadingGif`.
    static let loadingGif = Rswift.ImageResource(bundle: R.hostingBundle, name: "loadingGif")
    /// Image `locationBtn`.
    static let locationBtn = Rswift.ImageResource(bundle: R.hostingBundle, name: "locationBtn")
    /// Image `login`.
    static let login = Rswift.ImageResource(bundle: R.hostingBundle, name: "login")
    /// Image `logo`.
    static let logo = Rswift.ImageResource(bundle: R.hostingBundle, name: "logo")
    /// Image `mensajes`.
    static let mensajes = Rswift.ImageResource(bundle: R.hostingBundle, name: "mensajes")
    /// Image `mensajesnew`.
    static let mensajesnew = Rswift.ImageResource(bundle: R.hostingBundle, name: "mensajesnew")
    /// Image `menu`.
    static let menu = Rswift.ImageResource(bundle: R.hostingBundle, name: "menu")
    /// Image `moto_icon`.
    static let moto_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "moto_icon")
    /// Image `moto`.
    static let moto = Rswift.ImageResource(bundle: R.hostingBundle, name: "moto")
    /// Image `ofertaIcon`.
    static let ofertaIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "ofertaIcon")
    /// Image `operadora`.
    static let operadora = Rswift.ImageResource(bundle: R.hostingBundle, name: "operadora")
    /// Image `origenIcon`.
    static let origenIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "origenIcon")
    /// Image `origen`.
    static let origen = Rswift.ImageResource(bundle: R.hostingBundle, name: "origen")
    /// Image `referenciaIcon`.
    static let referenciaIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "referenciaIcon")
    /// Image `salir2`.
    static let salir2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "salir2")
    /// Image `sesion`.
    static let sesion = Rswift.ImageResource(bundle: R.hostingBundle, name: "sesion")
    /// Image `smsvozRec`.
    static let smsvozRec = Rswift.ImageResource(bundle: R.hostingBundle, name: "smsvozRec")
    /// Image `smsvoz`.
    static let smsvoz = Rswift.ImageResource(bundle: R.hostingBundle, name: "smsvoz")
    /// Image `solicitud`.
    static let solicitud = Rswift.ImageResource(bundle: R.hostingBundle, name: "solicitud")
    /// Image `stardorada`.
    static let stardorada = Rswift.ImageResource(bundle: R.hostingBundle, name: "stardorada")
    /// Image `stargris`.
    static let stargris = Rswift.ImageResource(bundle: R.hostingBundle, name: "stargris")
    /// Image `taxi_libre`.
    static let taxi_libre = Rswift.ImageResource(bundle: R.hostingBundle, name: "taxi_libre")
    /// Image `tiempo`.
    static let tiempo = Rswift.ImageResource(bundle: R.hostingBundle, name: "tiempo")
    /// Image `transporteMenu`.
    static let transporteMenu = Rswift.ImageResource(bundle: R.hostingBundle, name: "transporteMenu")
    /// Image `xoalogo1`.
    static let xoalogo1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "xoalogo1")
    
    /// `UIImage(named: "CLARO", bundle: ..., traitCollection: ...)`
    static func clarO(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clarO, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CNT", bundle: ..., traitCollection: ...)`
    static func cnT(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cnT, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "MOVISTAR", bundle: ..., traitCollection: ...)`
    static func movistaR(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.movistaR, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "backIcon", bundle: ..., traitCollection: ...)`
    static func backIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.backIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "callCenter", bundle: ..., traitCollection: ...)`
    static func callCenter(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.callCenter, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "camion", bundle: ..., traitCollection: ...)`
    static func camion(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.camion, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "camion_icon", bundle: ..., traitCollection: ...)`
    static func camion_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.camion_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "camioneta", bundle: ..., traitCollection: ...)`
    static func camioneta(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.camioneta, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "camioneta_icon", bundle: ..., traitCollection: ...)`
    static func camioneta_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.camioneta_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "chofer", bundle: ..., traitCollection: ...)`
    static func chofer(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chofer, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "clave", bundle: ..., traitCollection: ...)`
    static func clave(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clave, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "close", bundle: ..., traitCollection: ...)`
    static func close(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.close, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "compartir", bundle: ..., traitCollection: ...)`
    static func compartir(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.compartir, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "contactoIcon", bundle: ..., traitCollection: ...)`
    static func contactoIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.contactoIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "costo", bundle: ..., traitCollection: ...)`
    static func costo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.costo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "destinoIcon", bundle: ..., traitCollection: ...)`
    static func destinoIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.destinoIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "detalleIcon", bundle: ..., traitCollection: ...)`
    static func detalleIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.detalleIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "detalles", bundle: ..., traitCollection: ...)`
    static func detalles(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.detalles, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "distancia", bundle: ..., traitCollection: ...)`
    static func distancia(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.distancia, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "driverIcon", bundle: ..., traitCollection: ...)`
    static func driverIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.driverIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "evaluar", bundle: ..., traitCollection: ...)`
    static func evaluar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.evaluar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "furgon", bundle: ..., traitCollection: ...)`
    static func furgon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.furgon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "furgon_icon", bundle: ..., traitCollection: ...)`
    static func furgon_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.furgon_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "furgoneta", bundle: ..., traitCollection: ...)`
    static func furgoneta(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.furgoneta, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "furgoneta_icon", bundle: ..., traitCollection: ...)`
    static func furgoneta_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.furgoneta_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "grua", bundle: ..., traitCollection: ...)`
    static func grua(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.grua, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "grua_icon", bundle: ..., traitCollection: ...)`
    static func grua_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.grua_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "header", bundle: ..., traitCollection: ...)`
    static func header(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.header, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "home", bundle: ..., traitCollection: ...)`
    static func home(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "info", bundle: ..., traitCollection: ...)`
    static func info(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.info, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "infoMenu", bundle: ..., traitCollection: ...)`
    static func infoMenu(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.infoMenu, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "launch", bundle: ..., traitCollection: ...)`
    static func launch(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launch, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "llamar", bundle: ..., traitCollection: ...)`
    static func llamar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.llamar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "loadingGif", bundle: ..., traitCollection: ...)`
    static func loadingGif(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.loadingGif, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "locationBtn", bundle: ..., traitCollection: ...)`
    static func locationBtn(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.locationBtn, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "login", bundle: ..., traitCollection: ...)`
    static func login(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.login, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "logo", bundle: ..., traitCollection: ...)`
    static func logo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.logo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "mensajes", bundle: ..., traitCollection: ...)`
    static func mensajes(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.mensajes, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "mensajesnew", bundle: ..., traitCollection: ...)`
    static func mensajesnew(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.mensajesnew, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "menu", bundle: ..., traitCollection: ...)`
    static func menu(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.menu, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "moto", bundle: ..., traitCollection: ...)`
    static func moto(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.moto, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "moto_icon", bundle: ..., traitCollection: ...)`
    static func moto_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.moto_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ofertaIcon", bundle: ..., traitCollection: ...)`
    static func ofertaIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ofertaIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "operadora", bundle: ..., traitCollection: ...)`
    static func operadora(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.operadora, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "origen", bundle: ..., traitCollection: ...)`
    static func origen(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.origen, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "origenIcon", bundle: ..., traitCollection: ...)`
    static func origenIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.origenIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "referenciaIcon", bundle: ..., traitCollection: ...)`
    static func referenciaIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.referenciaIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "salir2", bundle: ..., traitCollection: ...)`
    static func salir2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.salir2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "sesion", bundle: ..., traitCollection: ...)`
    static func sesion(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.sesion, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "smsvoz", bundle: ..., traitCollection: ...)`
    static func smsvoz(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.smsvoz, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "smsvozRec", bundle: ..., traitCollection: ...)`
    static func smsvozRec(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.smsvozRec, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "solicitud", bundle: ..., traitCollection: ...)`
    static func solicitud(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.solicitud, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "stardorada", bundle: ..., traitCollection: ...)`
    static func stardorada(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stardorada, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "stargris", bundle: ..., traitCollection: ...)`
    static func stargris(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stargris, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "taxi_libre", bundle: ..., traitCollection: ...)`
    static func taxi_libre(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.taxi_libre, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "tiempo", bundle: ..., traitCollection: ...)`
    static func tiempo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tiempo, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "transporteMenu", bundle: ..., traitCollection: ...)`
    static func transporteMenu(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.transporteMenu, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "xoalogo1", bundle: ..., traitCollection: ...)`
    static func xoalogo1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.xoalogo1, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 8 nibs.
  struct nib {
    /// Nib `CallCenterViewCell`.
    static let callCenterViewCell = _R.nib._CallCenterViewCell()
    /// Nib `ContactoCell`.
    static let contactoCell = _R.nib._ContactoCell()
    /// Nib `OfertaViewCell`.
    static let ofertaViewCell = _R.nib._OfertaViewCell()
    /// Nib `OrigenCell`.
    static let origenCell = _R.nib._OrigenCell()
    /// Nib `Perfil2ViewCell`.
    static let perfil2ViewCell = _R.nib._Perfil2ViewCell()
    /// Nib `Perfil3ViewCell`.
    static let perfil3ViewCell = _R.nib._Perfil3ViewCell()
    /// Nib `PerfilViewCell`.
    static let perfilViewCell = _R.nib._PerfilViewCell()
    /// Nib `VoucherCell`.
    static let voucherCell = _R.nib._VoucherCell()
    
    /// `UINib(name: "CallCenterViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.callCenterViewCell) instead")
    static func callCenterViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.callCenterViewCell)
    }
    
    /// `UINib(name: "ContactoCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.contactoCell) instead")
    static func contactoCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.contactoCell)
    }
    
    /// `UINib(name: "OfertaViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.ofertaViewCell) instead")
    static func ofertaViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.ofertaViewCell)
    }
    
    /// `UINib(name: "OrigenCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.origenCell) instead")
    static func origenCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.origenCell)
    }
    
    /// `UINib(name: "Perfil2ViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.perfil2ViewCell) instead")
    static func perfil2ViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.perfil2ViewCell)
    }
    
    /// `UINib(name: "Perfil3ViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.perfil3ViewCell) instead")
    static func perfil3ViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.perfil3ViewCell)
    }
    
    /// `UINib(name: "PerfilViewCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.perfilViewCell) instead")
    static func perfilViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.perfilViewCell)
    }
    
    /// `UINib(name: "VoucherCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.voucherCell) instead")
    static func voucherCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.voucherCell)
    }
    
    static func callCenterViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> CallCenterViewCell? {
      return R.nib.callCenterViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? CallCenterViewCell
    }
    
    static func contactoCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ContactoViewCell? {
      return R.nib.contactoCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ContactoViewCell
    }
    
    static func ofertaViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> OfertaViewCell? {
      return R.nib.ofertaViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? OfertaViewCell
    }
    
    static func origenCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> OrigenViewCell? {
      return R.nib.origenCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? OrigenViewCell
    }
    
    static func perfil2ViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> Perfil2ViewCell? {
      return R.nib.perfil2ViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? Perfil2ViewCell
    }
    
    static func perfil3ViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> Perfil3ViewCell? {
      return R.nib.perfil3ViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? Perfil3ViewCell
    }
    
    static func perfilViewCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PerfilViewCell? {
      return R.nib.perfilViewCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PerfilViewCell
    }
    
    static func voucherCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> VoucherViewCell? {
      return R.nib.voucherCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? VoucherViewCell
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 6 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `CallCenterViewCell`.
    static let callCenterViewCell: Rswift.ReuseIdentifier<CallCenterViewCell> = Rswift.ReuseIdentifier(identifier: "CallCenterViewCell")
    /// Reuse identifier `CallCenter`.
    static let callCenter: Rswift.ReuseIdentifier<CallCenterViewCell> = Rswift.ReuseIdentifier(identifier: "CallCenter")
    /// Reuse identifier `MENUCELL`.
    static let menucelL: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "MENUCELL")
    /// Reuse identifier `PerfilViewCell`.
    static let perfilViewCell: Rswift.ReuseIdentifier<PerfilViewCell> = Rswift.ReuseIdentifier(identifier: "PerfilViewCell")
    /// Reuse identifier `Solicitudes`.
    static let solicitudes: Rswift.ReuseIdentifier<UIKit.UITableViewCell> = Rswift.ReuseIdentifier(identifier: "Solicitudes")
    /// Reuse identifier `typeCell`.
    static let typeCell: Rswift.ReuseIdentifier<MenuCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "typeCell")
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `Launch Screen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "Launch Screen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _ContactoCell.validate()
      try _OfertaViewCell.validate()
      try _OrigenCell.validate()
    }
    
    struct _CallCenterViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = CallCenterViewCell
      
      let bundle = R.hostingBundle
      let identifier = "CallCenterViewCell"
      let name = "CallCenterViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> CallCenterViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? CallCenterViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _ContactoCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "ContactoCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> ContactoViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ContactoViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "contactoIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'contactoIcon' is used in nib 'ContactoCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct _OfertaViewCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "OfertaViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> OfertaViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? OfertaViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "distancia", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'distancia' is used in nib 'OfertaViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "driverIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'driverIcon' is used in nib 'OfertaViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ofertaIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ofertaIcon' is used in nib 'OfertaViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "stardorada", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'stardorada' is used in nib 'OfertaViewCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct _OrigenCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "OrigenCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> OrigenViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? OrigenViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "destinoIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'destinoIcon' is used in nib 'OrigenCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "detalleIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'detalleIcon' is used in nib 'OrigenCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ofertaIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ofertaIcon' is used in nib 'OrigenCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "origenIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'origenIcon' is used in nib 'OrigenCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "referenciaIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'referenciaIcon' is used in nib 'OrigenCell', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct _Perfil2ViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "Perfil2ViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> Perfil2ViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? Perfil2ViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _Perfil3ViewCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "Perfil3ViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> Perfil3ViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? Perfil3ViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _PerfilViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = PerfilViewCell
      
      let bundle = R.hostingBundle
      let identifier = "PerfilViewCell"
      let name = "PerfilViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> PerfilViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? PerfilViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _VoucherCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "VoucherCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> VoucherViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? VoucherViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "Launch Screen"
      
      static func validate() throws {
        if UIKit.UIImage(named: "launch", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'launch' is used in storyboard 'Launch Screen', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let callCenter = StoryboardViewControllerResource<CallCenterController>(identifier: "CallCenter")
      let completadaView = StoryboardViewControllerResource<CompletadaController>(identifier: "completadaView")
      let inicioNavController = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "InicioNavController")
      let inicioView = StoryboardViewControllerResource<InicioController>(identifier: "InicioView")
      let listaSolPdtes = StoryboardViewControllerResource<SolicitudesTableController>(identifier: "ListaSolPdtes")
      let loginNavigationController = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "LoginNavigationController")
      let loginView = StoryboardViewControllerResource<LoginController>(identifier: "LoginView")
      let name = "Main"
      let ofertasView = StoryboardViewControllerResource<OfertasController>(identifier: "ofertasView")
      let perfil = StoryboardViewControllerResource<PerfilController>(identifier: "Perfil")
      let solPendientes = StoryboardViewControllerResource<SolPendController>(identifier: "SolPendientes")
      let transpMenuView = StoryboardViewControllerResource<TransporteMenuController>(identifier: "TranspMenuView")
      
      func callCenter(_: Void = ()) -> CallCenterController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: callCenter)
      }
      
      func completadaView(_: Void = ()) -> CompletadaController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: completadaView)
      }
      
      func inicioNavController(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: inicioNavController)
      }
      
      func inicioView(_: Void = ()) -> InicioController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: inicioView)
      }
      
      func listaSolPdtes(_: Void = ()) -> SolicitudesTableController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: listaSolPdtes)
      }
      
      func loginNavigationController(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: loginNavigationController)
      }
      
      func loginView(_: Void = ()) -> LoginController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: loginView)
      }
      
      func ofertasView(_: Void = ()) -> OfertasController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: ofertasView)
      }
      
      func perfil(_: Void = ()) -> PerfilController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: perfil)
      }
      
      func solPendientes(_: Void = ()) -> SolPendController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: solPendientes)
      }
      
      func transpMenuView(_: Void = ()) -> TransporteMenuController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: transpMenuView)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "chofer", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'chofer' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "close", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'close' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "costo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'costo' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "destinoIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'destinoIcon' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "distancia", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'distancia' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "header", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'header' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "home", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'home' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "llamar", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'llamar' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "locationBtn", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'locationBtn' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "login", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'login' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "logo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'logo' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "mensajes", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'mensajes' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "menu", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'menu' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "ofertaIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'ofertaIcon' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "origen", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'origen' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "origenIcon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'origenIcon' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "salir2", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'salir2' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "smsvoz", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'smsvoz' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "stargris", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'stargris' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "tiempo", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'tiempo' is used in storyboard 'Main', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
        if _R.storyboard.main().callCenter() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'callCenter' could not be loaded from storyboard 'Main' as 'CallCenterController'.") }
        if _R.storyboard.main().inicioNavController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'inicioNavController' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.main().inicioView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'inicioView' could not be loaded from storyboard 'Main' as 'InicioController'.") }
        if _R.storyboard.main().listaSolPdtes() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'listaSolPdtes' could not be loaded from storyboard 'Main' as 'SolicitudesTableController'.") }
        if _R.storyboard.main().loginNavigationController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'loginNavigationController' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.main().loginView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'loginView' could not be loaded from storyboard 'Main' as 'LoginController'.") }
        if _R.storyboard.main().perfil() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'perfil' could not be loaded from storyboard 'Main' as 'PerfilController'.") }
        if _R.storyboard.main().solPendientes() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'solPendientes' could not be loaded from storyboard 'Main' as 'SolPendController'.") }
        if _R.storyboard.main().transpMenuView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'transpMenuView' could not be loaded from storyboard 'Main' as 'TransporteMenuController'.") }
        if _R.storyboard.main().completadaView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'completadaView' could not be loaded from storyboard 'Main' as 'CompletadaController'.") }
        if _R.storyboard.main().ofertasView() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'ofertasView' could not be loaded from storyboard 'Main' as 'OfertasController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
